# dnans_smb.yaml
# Rename this file in production as needed (e.g., to snand_smb.yaml)
---
- hosts: docker_hosts
  become: yes
  vars_files:
    - platform_vars.yaml   # Shared variable file with project_root and smb_share_name

  tasks:
    - name: Install Samba
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Create shared directory
      file:
        path: "{{ smb_share_path }}"  # Defined in platform_vars.yaml as {{ project_root }}/shared
        state: directory
        mode: "0777"

    - name: Configure Samba share
      blockinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [{{ smb_share_name }}]
          path = {{ smb_share_path }}
          browseable = yes
          read only = no
          guest ok = yes
          create mask = 0777
          directory mask = 0777

    - name: Restart Samba
      service:
        name: smbd
        state: restarted
