# dnans_wordpress.yaml
# Rename this file in production as needed (e.g., to snand_wordpress.yaml)
---
- hosts: docker_hosts
  become: yes
  vars_files:
    - platform_vars.yaml   # Shared variable file

  tasks:
    - name: Create WordPress project directory
      file:
        path: "{{ project_root }}/wordpress"
        state: directory
        mode: "0755"

    - name: Deploy .env file for WordPress
      template:
        src: "wordpress.env.j2"
        dest: "{{ project_root }}/wordpress/.env"
        mode: "0600"

    - name: Deploy Docker Compose file for WordPress
      copy:
        src: "docker-compose-wordpress.yml"
        dest: "{{ project_root }}/wordpress/docker-compose.yml"
        mode: "0644"

    - name: Start WordPress stack
      shell: docker compose up -d
      args:
        chdir: "{{ project_root }}/wordpress"
