---
- name: Ensure Docker is installed
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create Docker bridge network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    driver: bridge
    state: present

- name: Ensure Traefik data directories exist
  file:
    path: "{{ docker_projects_path }}/traefik/traefik/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - data  # For storing Traefik's dynamic config or certificates

- name: Generate .env file for Traefik
  template:
    src: .env.j2
    dest: "{{ docker_projects_path }}/traefik/.env"
    mode: '0640'

- name: Copy Traefik Docker Compose file
  copy:
    src: docker-compose.yaml.j2
    dest: "{{ docker_projects_path }}/traefik/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Launch Traefik with Docker Compose
  community.docker.docker_compose:
    project_src: "{{ project_path }}/docker/traefik"
    state: present
    pull: yes
    recreate: yes
    remove_orphans: yes
  notify:
    - Restart Docker services