---
# Check if the vault password file is defined
- name: Check if vault password file is defined
  fail:
    msg: >
      The `vault_password_file` must be set in `ansible.cfg` or provided at runtime
      using the `--vault-password-file` option.
  when: not (ansible_vault_password_file | default(None))

# Check if vault.yaml exists
- name: Check if vault.yaml exists
  stat:
    path: group_vars/vault.yaml
  register: vault_file

- name: Create vault.yaml if it doesn't exist
  include_tasks: create_vault.yaml
  when: not vault_file.stat.exists

- name: Fail if vault.yaml exists but --ask-become-password or become password is not set
  fail:
    msg: >
      This playbook must be run with `--ask-become-pass` or have the `ansible_become_password`
      set in the vault. Edit `group_vars/vault.yaml` to include the `ansible_become_password`.
  when: not (ansible_become_password | default(None)) and not vault_file.stat.exists
