# dnans.yaml
# Rename this file in production as needed (e.g., to snand.yaml)
---
- hosts: docker_hosts
  become: yes
  vars_files:
    - platform_vars.yml   # Centralized variables file, may remain the same across environments

  roles:
    - dnans_host          # Base Docker host setup
#    - dnans_smb           # SMB configuration
#    - dnans_ingress       # traefik/cloudflare/letsencrypt
#    - dnans_immich        # immich docker compose setup
#    - dnans_wordpress     # WordPress Docker Compose setup
    # Additional roles can be added here as needed
