# inventory_discovery.yaml
---
- hosts: debian_servers
  gather_facts: yes
  tasks:
    - name: Gather hardware and system information
      setup:

    - name: Display disk and partition facts
      debug:
        var: ansible_facts.devices
