FROM klakegg/hugo:0.110.0-ext-alpine

WORKDIR /src

# Add a script to watch for build triggers
COPY ./watch.sh /watch.sh
RUN chmod +x /watch.sh

# Default command will monitor for changes and build
CMD ["/watch.sh"]