---
# Step 1: Load default vault template
- name: Copy default vault template to temporary location
  copy:
    src: vault.default.yaml
    dest: /tmp/vault.default.yaml
  check_mode: no  # Always copy the file to ensure consistency

# Step 2: Parse the default vault values
- name: Parse default vault values
  slurp:
    src: /tmp/vault.default.yaml
  register: default_vault_content

- name: Convert default vault values to variable
  set_fact:
    default_vault: "{{ default_vault_content['content'] | b64decode | from_yaml }}"

# Step 3: Check if vault.yaml exists
- name: Check if vault.yaml exists
  stat:
    path: "{{ playbook_dir }}/vault.yaml"
  register: vault_file

# Step 4: Ensure the vault.yaml is encrypted if it exists
- name: Check if vault.yaml is encrypted
  command: "ansible-vault view {{ playbook_dir }}/vault.yaml"
  register: vault_encryption_status
  ignore_errors: true
  when: vault_file.stat.exists

- name: Fail if vault.yaml is unencrypted
  fail:
    msg: "The vault.yaml file exists but is unencrypted. Please encrypt it manually or remove it."
  when: vault_file.stat.exists and vault_encryption_status.rc != 0

# Step 5: Decrypt and load existing vault.yaml if encrypted
- name: Parse existing vault.yaml content
  set_fact:
    existing_vault: "{{ vault_encryption_status.stdout | from_yaml }}"
  when: vault_file.stat.exists and vault_encryption_status.rc == 0

# Step 6: Initialize a new encrypted vault.yaml if missing
- name: Prepare new vault content
  set_fact:
    new_vault_content: >-
      {{
        default_vault | combine({
          'immich_database_password': (lookup('password', '/dev/null length=16 chars=ascii_letters,digits')),
          'wordpress_database_password': (lookup('password', '/dev/null length=16 chars=ascii_letters,digits')),
          'wordpress_database_root_password': (lookup('password', '/dev/null length=31 chars=ascii_letters,digits')),
          'smb_password': (lookup('password', '/dev/null length=16 chars=ascii_letters,digits'))
        })
      }}
  when: not vault_file.stat.exists

- name: Save new vault.yaml content to a temporary file
  copy:
    content: "{{ new_vault_content | to_nice_yaml }}"
    dest: "/tmp/vault.yaml"
    mode: '0600'
  when: not vault_file.stat.exists

- name: Encrypt and move the new vault.yaml to the project directory
  command: "ansible-vault encrypt /tmp/vault.yaml --output={{ playbook_dir }}/vault.yaml"
  when: not vault_file.stat.exists

# Step 7: Merge and update vault.yaml with new values
- name: Merge vaults and generate missing sensitive values
  set_fact:
    new_vault_content: >-
      {{
        default_vault | combine(existing_vault, recursive=True) | combine({
          'immich_database_password': (existing_vault.immich_database_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits'))),
          'immich_database_root_password': (existing_vault.immich_database_root_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits'))),
          'wordpress_db_password': (existing_vault.wordpress_db_password | default(lookup('password', '/dev/null length=16 chars=ascii_letters,digits'))),
          'wordpress_db_root_password': (existing_vault.wordpress_db_root_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits'))),
          'smb_password': (existing_vault.smb_password | default(lookup('password', '/dev/null length=16 chars=ascii_letters,digits')))
        })
      }}
  when: vault_file.stat.exists

# Step 8: Save the merged vault content back to the file
- name: Save updated vault.yaml content to a temporary file
  copy:
    content: "{{ new_vault_content | to_nice_yaml }}"
    dest: "/tmp/vault.yaml"
    mode: '0600'

- name: Encrypt and replace vault.yaml
  command:
    cmd: "ansible-vault encrypt /tmp/vault.yaml --output={{ playbook_dir }}/vault.yaml"
  args:
    removes: "/tmp/vault.yaml"
  become: false

# Debug for confirmation
- debug:
    var: new_vault_content
