- name: Backup original smb.conf
  copy:
    src: /etc/samba/smb.conf
    dest: /etc/samba/smb.conf.bak
    remote_src: yes
    backup: yes

- name: Ensure only specified shares exist in smb.conf
  blockinfile:
    path: /etc/samba/smb.conf
    marker: "; ANSIBLE MANAGED BLOCK - SMB CONFIG"
    block: |
      [global]
      workgroup = WORKGROUP
      security = user
      map to guest = Bad User
      guest account = nobody

      [shared]
      path = /snand/shared
      browseable = yes
      writable = yes
      guest ok = yes
      public = yes
      create mask = 0666
      directory mask = 0777
      force user = nobody
      force group = nogroup
      read only = no
      veto files = /lost+found/
      delete veto files = no

      [{{ ansible_user }}]
      path = /home/{{ ansible_user }}
      browseable = yes
      writable = yes
      valid users = {{ ansible_user }}
      create mode = 0750
      directory mode = 0750
  notify:
    - Restart Samba

- name: Ensure permissions for /snand/shared
  file:
    path: /snand/shared
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup

- name: Ensure Samba user {{ ansible_user }} exists
  shell: |
    (echo "{{ smb_password }}"; echo "{{ smb_password }}") | smbpasswd -s -a "{{ ansible_user }}"
  ignore_errors: true
  changed_when: false

- name: Update Samba password for {{ ansible_user }}
  shell: |
    (echo "{{ smb_password }}"; echo "{{ smb_password }}") | smbpasswd -s "{{ ansible_user }}"
  when: ansible_user is defined
  changed_when: false

- name: Remove unnecessary shares from smb.conf
  lineinfile:
    path: /etc/samba/smb.conf
    state: absent
    regexp: '^\[(?!shared|{{ ansible_user }})\w+\]'
  notify:
    - Restart Samba
