# roles/dnans_host/tasks/main.yaml
---

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
      - lazydocker
      - samba
      - nfs-kernel-server
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Reboot system
  reboot:
    msg: "Rebooting to apply hostname and IP changes"
    connect_timeout: 60
