# roles/dnans_host/tasks/main.yaml
---
- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
      - samba
      - nfs-kernel-server
    state: present
    update_cache: yes

- name: Add user to Docker group
  user:
    name: "{{ sudo_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
