# roles/dnans_host/tasks/main.yaml
---

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
      - samba
      - nfs-kernel-server
    state: present

- name: Download and run LazyDocker install script
  shell: |
    curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | DIR=/usr/local/bin bash
  args:
    creates: /usr/local/bin/lazydocker

- name: Ensure LazyDocker binary is executable
  file:
    path: /usr/local/bin/lazydocker
    mode: '0755'
    state: file

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Reboot system
  reboot:
    msg: "Rebooting to apply hostname and IP changes"
    connect_timeout: 60
