version: '3'

services:
  flask:
    build: ./flask
    container_name: myblog-flask
    restart: unless-stopped
    volumes:
      - ./flask/app:/app
      - ./shared:/shared
      - /snand/shared/myblog:/snand/shared/myblog
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secure-key-here
      - HUGO_SITE_PATH=/shared/generated
      - CONTENT_PATH=/shared/content
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myblog-admin.rule=Host(`admin.yourdomain.com`)"
      - "traefik.http.routers.myblog-admin.entrypoints=websecure"
      - "traefik.http.routers.myblog-admin.tls=true"
      - "traefik.http.services.myblog-admin.loadbalancer.server.port=5000"
      # Protected paths for authenticated content
      - "traefik.http.routers.myblog-internal.rule=Host(`yourdomain.com`) && PathPrefix(`/internal`)"
      - "traefik.http.routers.myblog-internal.entrypoints=websecure"
      - "traefik.http.routers.myblog-internal.tls=true"
      - "traefik.http.services.myblog-internal.loadbalancer.server.port=5000"
      # API endpoints
      - "traefik.http.routers.myblog-api.rule=Host(`yourdomain.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.myblog-api.entrypoints=websecure"
      - "traefik.http.routers.myblog-api.tls=true"
      - "traefik.http.services.myblog-api.loadbalancer.server.port=5000"

  hugo:
    build: ./hugo
    container_name: myblog-hugo
    restart: unless-stopped
    volumes:
      - ./hugo:/src
      - ./shared:/shared
      - /snand/shared/myblog:/snand/shared/myblog
    environment:
      - HUGO_WATCH=true
      - HUGO_DESTINATION=/shared/generated
      - HUGO_THEME=your-theme
      - HUGO_BASEURL=https://yourdomain.com
    networks:
      - proxy
    depends_on:
      - flask

  nginx:
    image: nginx:alpine
    container_name: myblog-nginx
    restart: unless-stopped
    volumes:
      - ./shared/generated:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myblog.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.myblog.entrypoints=websecure"
      - "traefik.http.routers.myblog.tls=true"
      - "traefik.http.services.myblog.loadbalancer.server.port=80"
      # Exclude paths that should be handled by Flask
      - "traefik.http.routers.myblog.middlewares=myblog-path-strip"
      - "traefik.http.middlewares.myblog-path-strip.stripprefix.prefixes=/internal,/api"

networks:
  proxy:
    external: true