# debian_host.yaml
---
- hosts: debian_servers
  become: yes
  vars_files:
    - platform_vars.yaml

  tasks:
    - name: Install sudo
      apt:
        name: sudo
        state: present
        update_cache: yes

    - name: Add user to sudoers group
      user:
        name: "{{ sudo_user }}"
        groups: sudo
        append: yes
        state: present

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker and Docker Compose dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to Docker group
      user:
        name: "{{ sudo_user }}"
        groups: docker
        append: yes

    - name: Install lazydocker and mc
      apt:
        name:
          - lazydocker
          - mc
        state: present
