---
- name: Check and prompt for ansible_become_pass
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  tasks:
    - name: Prompt for ansible_become_pass if not set
      vars_prompt:
        - name: "input_become_pass"
          prompt: "Enter the ansible_become_pass (sudo password):"
          private: yes
      when: ansible_become_pass is not defined or ansible_become_pass == ""

    - name: Set ansible_become_pass if prompted
      set_fact:
        ansible_become_pass: "{{ input_become_pass }}"
      when: input_become_pass is defined

- name: Ensure sensitive variables in vault.yaml are complete
  hosts: localhost
  gather_facts: false
  roles:
    - dnans_vault

- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    - dnans_docker
    - dnans_wordpress
