---
- name: Ensure sensitive variables in vault.yaml are complete
  hosts: localhost
  become: yes
  gather_facts: false
  roles:
    - dnans_vault

- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    - dnans_docker
    - dnans_wordpress
    - dnans_immich
