# dnans.yaml
---
- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    # Additional roles will be added as the project expands
    # - dnans_ingress

  tasks:
    - name: Debug ansible_become_pass
      debug:
        msg: "Become password is: {{ ansible_become_pass }}"

    - name: Ping the server
      ping:
      become: no  # Disable sudo for this task