# dnans.yaml
---
- name: Configure dnans server
  hosts: servers
  become: yes
  roles:
    - dnans_host          # Base server setup (Docker, LazyDocker, etc.)
    # Additional roles will be added as the project expands
    # - dnans_smb
    # - dnans_ingress
