# dnans.yaml
---
- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    # Additional roles will be added as the project expands
    # - dnans_ingress
- name: Ping servers
  hosts: all
  tasks:
    - name: Ping the server
      ping: