---
- name: Configure dnans server
  hosts: servers
  become: yes
  gather_facts: true
  vars_files:
    - vault.yaml
  roles:
    - dnans_vault
    - dnans_host
    - dnans_smb
    - dnans_docker
    - dnans_wordpress
