---
- name: Check and prompt for ansible_become_pass
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  vars:
    ansible_become_pass: "{{ ansible_become_pass | default(None) }}"
  pre_tasks:
    - name: Prompt for ansible_become_pass if not set
      ansible.builtin.pause:
        prompt: "Enter the ansible_become_pass (sudo password):"
      register: become_pass_input
      when: ansible_become_pass is not defined
    - name: Set ansible_become_pass from prompt
      set_fact:
        ansible_become_pass: "{{ become_pass_input.user_input }}"
      when: ansible_become_pass is not defined
  tasks:
    - name: Display ansible_become_pass
      debug:
        msg: "ansible_become_pass is set."

- name: Ensure sensitive variables in vault.yaml are complete
  hosts: localhost
  gather_facts: false
  roles:
    - dnans_vault

- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    - dnans_docker
    - dnans_wordpress
