---
- name: Check and prompt for ansible_become_pass
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  tasks:
    - name: Check if ansible_become_pass is defined
      set_fact:
        prompt_for_become_pass: "{{ ansible_become_pass is not defined or ansible_become_pass == '' }}"

    - name: Prompt for ansible_become_pass if not set
      pause:
        prompt: "Enter the ansible_become_pass (sudo password):"
        echo: no
      register: become_pass_input
      when: prompt_for_become_pass

    - name: Set ansible_become_pass variable
      set_fact:
        ansible_become_pass: "{{ become_pass_input.user_input }}"
      when: prompt_for_become_pass

- name: Ensure sensitive variables in vault.yaml are complete
  hosts: localhost
  gather_facts: false
  roles:
    - dnans_vault

- name: Configure dnans server
  hosts: servers
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - dnans_host
    - dnans_smb
    - dnans_docker
    - dnans_wordpress
