- name: Ensure vault.yaml is complete
  hosts: localhost
  tasks:
    - name: Load existing vault.yaml
      slurp:
        src: vault.yaml
      register: vault_content
      ignore_errors: true

    - name: Parse vault.yaml content if exists
      set_fact:
        existing_vault: "{{ vault_content['content'] | b64decode | from_yaml }}"
      when: vault_content is defined

    - name: Initialize empty vault if missing
      set_fact:
        existing_vault: {}

    - name: Ensure sensitive variables are set
      set_fact:
        updated_vault: >-
          {{
            existing_vault | combine({
              'immich_database_password': (existing_vault.immich_database_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits'))),
              'immich_database_root_password': (existing_vault.immich_database_root_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits'))),
              'wordpress_db_password': (existing_vault.wordpress_db_password | default(lookup('password', '/dev/null length=16 chars=ascii_letters,digits'))),
              'wordpress_db_root_password': (existing_vault.wordpress_db_root_password | default(lookup('password', '/dev/null length=31 chars=ascii_letters,digits')))
            })
          }}

    - name: Save updated vault.yaml
      copy:
        content: "{{ updated_vault | to_nice_yaml }}"
        dest: vault.yaml
        owner: root
        group: root
        mode: '0600'
      no_log: true
