---
services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    container_name: grav
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/grav/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.grav.entrypoints=web
      - traefik.http.routers.grav.rule=Host(`https://grav.dnans.org`)
      - traefik.http.routers.grav.tls.certresolver=letsencrypt
      - traefik.http.routers.grav.tls=true
#      - traefik.http.services.grav.loadbalancer.server.port=2283
    # ports:
    #   - 8181:80
    restart: unless-stopped
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true